### ISSUE TITLE
$().on() doesn't work

### ISSUE THREAD

**Issue by trikadin** [philpl/sprint#17]
http://codepen.io/trikadin/pen/VvybWv

**Comment by abdala** [comment]
@trikadin, I think it is right to:

```javascript
$(document).on('click', '#main', () => {alert('click on #main')});
```

Works for me. :)

**Comment by trikadin** [comment]
@abdala you listen the whole document for click event, but trigger callback only if event.target == #main.

**Comment by abdala** [comment]
Yup! You're right. Perhaps Sprint could do something like Zepto. https://github.com/madrobby/zepto/blob/master/src/event.js#L174

**Comment by philplckthun** [comment]
@abdala @trikadin Hm indeed, this should be refactored to work for trikadin's example

**Comment by kurtextrem** [comment]
Any solution yet?

**Comment by trikadin** [comment]
@philplckthun, I rolled back to the original repo)

**Comment by kurtextrem** [comment]
@philpl Anything new?

**Comment by kurtextrem** [comment]
Nice! :+1:
